### ISSUE TITLE
H2 makes crash container on startup 

### ISSUE THREAD

**Issue by Hyurt** [rongfengliang/cloudbeaver-docker#1]
I'm launching it from docker-compose, after build container crashes

``` 
cloudbeaver_1  | 2020-05-22 11:27:20.354 - Error initializing database
cloudbeaver_1  | org.jkiss.dbeaver.DBException: Error creating driver 'H2 Embedded' instance.
cloudbeaver_1  | Most likely required jar files are missing.
cloudbeaver_1  | You should configure jars in driver settings.
cloudbeaver_1  |
cloudbeaver_1  | Reason: can't load driver class 'org.h2.Driver'
cloudbeaver_1  | 	at org.jkiss.dbeaver.registry.driver.DriverDescriptor.loadDriver(DriverDescriptor.java:964)
cloudbeaver_1  | 	at org.jkiss.dbeaver.registry.driver.DriverDescriptor.loadDriver(DriverDescriptor.java:939)
cloudbeaver_1  | 	at org.jkiss.dbeaver.registry.driver.DriverDescriptor.getDriverInstance(DriverDescriptor.java:572)
cloudbeaver_1  | 	at io.cloudbeaver.server.CBDatabase.initialize(CBDatabase.java:95)
cloudbeaver_1  | 	at io.cloudbeaver.server.CBApplication.initializeDatabase(CBApplication.java:224)
cloudbeaver_1  | 	at io.cloudbeaver.server.CBApplication.start(CBApplication.java:194)
cloudbeaver_1  | 	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
cloudbeaver_1  | 	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
cloudbeaver_1  | 	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
cloudbeaver_1  | 	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
cloudbeaver_1  | 	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
cloudbeaver_1  | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
cloudbeaver_1  | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
cloudbeaver_1  | 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
cloudbeaver_1  | 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
cloudbeaver_1  | 	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:657)
cloudbeaver_1  | 	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:594)
cloudbeaver_1  | 	at org.eclipse.equinox.launcher.Main.run(Main.java:1447)
cloudbeaver_1  | 	at org.eclipse.equinox.launcher.Main.main(Main.java:1420)
cloudbeaver_1  | Caused by: java.lang.ClassNotFoundException: org.h2.Driver
cloudbeaver_1  | 	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
cloudbeaver_1  | 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
cloudbeaver_1  | 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
cloudbeaver_1  | 	at java.base/java.lang.Class.forName0(Native Method)
cloudbeaver_1  | 	at java.base/java.lang.Class.forName(Class.java:398)
cloudbeaver_1  | 	at org.jkiss.dbeaver.registry.driver.DriverDescriptor.loadDriver(DriverDescriptor.java:962)
cloudbeaver_1  | 	... 18 more
cloudbeaver_1  | 2020-05-22 11:27:20.365 - Shutdown Core...
cloudbeaver_1  | 2020-05-22 11:27:20.436 - Shutdown completed in 71ms
```

Before the crash I have `Total database drivers: 81 (81)` BUT drivers jaybird, h2_embedded, derby_server, sqlite_jdbc, yandex_clickhouse, mysql8, mariaDB and postgres-jdbc missing from `drivers/postgresql`  

Also, maybe pushing the image on dockerhub would be great - build is a bit long for some users that just want to quickly have a look

**Comment by ItsNoted** [comment]
Doesn't work on Synology.

sh: 0: Can't open /app/run-server.sh | stdout
-- | --

**Comment by Hyurt** [comment]
@geekaroni you don't provide enough information and not directly related to this issue. 

Did you clone the whole project for building the image ?

**Comment by rongfengliang** [comment]
@Hyurt   i have push one docker image `dalongrong/cloudbeaver` , but not latest version ,this maybe  caused by h2  library not including in the package,maybe copy deps jar library will  works 
@geekaroni  `/app/run-server.sh `  not same as  offical shell file,i do some change for working wtih docker

**Comment by Hyurt** [comment]
Works great, thanks @rongfengliang 

Can't wait what they will offer next!
